# -*- coding: utf-8 -*-
"""Python_assignment_basic1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YxEptMyJyjf_4rCKA3Etm0TV5UYyqWf

1.Explain the key features of python that makes it a proper choice for programming?

Ans- Features:-
     1. most uses in data industry.
     2. ease of learning ,very easy to learn
     3.wide range of application-
       -backend,frontend web development
       -making data pipeline
       -connect to database
       -web scrapping
       -automation
       -machine learning,NLP,LLM
       -data visualization
       -data engineering
       -image processing
       -vast numbers of libraries for diffent domain  
      these features makes the pyhton ,the proper choice for programming.
"""



"""2. Describe the role of predefined keywords in python and provide examples how they are used in a program?"""

# here is the keywords in python
help('keywords')

#Example-1(if,True,False,else,elif)
assignment_marks=True
attempt=False
if assignment_marks:
   if attempt:
    print('pass')
   else:
    print("got the pass marks but attempt is expired")
elif attempt:
  print('you fail to get the pass marks do it again you have attempts left ')
else:
  print('you are totally fail')


# Example-2(for, in )
for i in range(10):
  print("*",end=" ")

"""3. Compare and contrast mutable and immutable objects in pyhton with example."""

list=[1,3,7,9,'rupak','manish']
tuple=(1,2,7,9,'rupak','manish')

list[-2]='pratick'  # this is mutable
list

# tuple[-2]='pratick'   # 'tuple' object does not support item assignment
# tuple

s="India will win the world_cup in 2024"
print(s.replace("India","Australia"))  # copy
s                                      # original

# contrast:-
# so in mutable data structure when we want to change the element of it , it just directly
#  change the element in the memory location is was stored before.

# in case of immutable data structure when we want to manipulate it ,
# it will first create a new memory location then manipulate thereafter.
# So  when we call the original data structure it will remain same.

# Compare:-
# in both case data manipulation happens but one in the original data structure(mutable),
# in another one(immutable) it happens in a new memory location (copy).

"""4. Discuss the different operators in python and provide example how they are used?

Ans-  Operators:-
       1.Arithmatic operator  [+ , - , * , / , % , ** ]
       2. Comparsion operator [ == , != , > , < , >= , <= ]
       3. Logical operator [ AND , OR , NOT ]
       4. Bitwise operator [ & , | , - , ^ , << , >> ]
       5. Assignment opearator [ = , += , -= , *= , /= ]
       6. Membership operator [ in , not in]
       7. identity operator [ is , is not]

       

"""

# arithmatic operator
a=10
b=2
print(f"the {b} to the power of {a} is {a**b}")
print(f"{b} * {a} is {a*b}")
print(f"{b} * {a} is {a/b}")

# comparision operator:
temperature=29

if temperature >=49:
  print('extreme hot condition')
elif temperature >= 35 and temperature<=45:
  print('very hot')
elif temperature >= 28 and temperature<=35:
  print('hot weather')
else:
  print('comfortable weather')


# logical operator:

print(True and True)
print(True and False)
print(True or False)
print(True or True)
print(False or False)
print(not False)


# Assignment opeartor
a= 1                    # = assignment operator
while a<= 10:
  print(a)
  a+=1                  # += assignment operator


# membership operator:
for i in range(5):
   print(i)

'd' not in "delhi"

# identity operator:
'delhi' is 'delhi'

"""5.Explain the concept of type casting in python with example."""

# type casting is a process to convert one data type to another
# but alaways not all conversion is possible like- string to integer

# example-
a= 2024

print('a is an integer')
print(type(a))
print('now convert it into string')
b=str(a)
print(f"this is actually string={b}")
print(type(b))

print('second type')

a= '2024'
print(f"in this case {a} is a string")
print(type(a))
print('now convert it into an integer')
c=int(a)
print(type(c))

# a = "Shantanu"
# d=int(a)            # this conversion is not possible
# print(type(d))

# there are some more type casting functions like-float(),list(),set(),dict()

"""6. How do conditional statement work in pyhton?illustrate with example"""

# mainly 3 type of conditional are there

# example-1  (if-else)
schooltime=9.45
if schooltime>10.00:
   print("school gate is closed for the day")
else:
  print("you can go to the class")

# Example-2  (if-elif-else)
time=1.00
if 4.30 < time <= 6.00:
        print(f'{time}: dawn')
elif 6.00 < time <= 12.00:
        print(f'{time}: morning')
elif 12.00 < time <= 13.00:
        print(f'{time}: noon')
elif 13.00 < time <= 16.00:
        print(f'{time}: afternoon')
elif 16.00 < time <= 19.00:
        print(f'{time}: evening')
elif 19.00 < time <= 23.00:
        print(f'{time}: night')
else:
    print(f'{time}: late night')

# example-3 [nested if-else ](if there is a weekend and if weather is sunny then go for picnic ,
#            if weather is not sunny then stay at home ,
#            otheriwse go to work)
is_weekend=True
is_sunny=False

if is_weekend:
    if is_sunny:
      print("wow it is weekend and it is sunny you can go to picnic")
    else:
      print('it is weekned but unfortunately weather is bad so stay at home')
elif is_sunny:
  print("weeknd is over ,weather is good so go to work")
else:
   print("this is not weeknend but due to bad weather you don't have to go for work")


# example-4(student and teacher)[nested if-else]
is_student=False
is_teacher=False

if is_student:
   if is_teacher:
      print('student and teacher both')
   else:
      print('student only')
else:
 if is_teacher:
   print('only a teacher')
 else:
   print('neither a teacher nor a student')

"""7. describe the different types of loops in python and their use cases with examples?"""

# while loops-(reverse list operation)
l=['delhi','mumbai','kolkata','banana',2,1]
i=len(l)-1
while 0<i<len(l):
   print(l[i])
   i-=1

# while loops-(string operation)
s='Shantanu'
i=0
while i<len(s):
  print(s[i])
  i+=1

# for loops-(product table form 1 to 5)
for i in range(1,6):
    for j in range(1,11):
      product=i*j
      print(f"{i}*{j}={product}")
    print()